export const typeIcons: Record<string, string> = {
  normal: "/types/Pokemon_Type_Icon_Normal.png",
  fire: "/types/Pokemon_Type_Icon_Fire.png",
  water: "/types/Pokemon_Type_Icon_Water.png",
  electric: "/types/Pokemon_Type_Icon_Electric.png",
  grass: "/types/Pokemon_Type_Icon_Grass.png",
  ice: "/types/Pokemon_Type_Icon_Ice.png",
  fighting: "/types/Pokemon_Type_Icon_Fighting.png",
  poison: "/types/Pokemon_Type_Icon_Poison.png",
  ground: "/types/Pokemon_Type_Icon_Ground.png",
  flying: "/types/Pokemon_Type_Icon_Flying.png",
  psychic: "/types/Pokemon_Type_Icon_Psychic.png",
  bug: "/types/Pokemon_Type_Icon_Bug.png",
  rock: "/types/Pokemon_Type_Icon_Rock.png",
  ghost: "/types/Pokemon_Type_Icon_Ghost.png",
  dragon: "/types/Pokemon_Type_Icon_Dragon.png",
  dark: "/types/Pokemon_Type_Icon_Dark.png",
  steel: "/types/Pokemon_Type_Icon_Steel.png",
  fairy: "/types/Pokemon_Type_Icon_Fairy.png",
}